services:
  postgres:
    image: postgres:16-alpine
    container_name: sassfr_postgres
    restart: unless-stopped
    environment:
      POSTGRES_USER: sassfr
      POSTGRES_PASSWORD: sassfr
      POSTGRES_DB: sassfr
    ports:
      - "5433:5432"
    volumes:
      - sassfr_postgres_data:/var/lib/postgresql/data

  adminer:
    image: adminer:latest
    container_name: sassfr_adminer
    restart: unless-stopped
    ports:
      - "8080:8080"
    depends_on:
      - postgres

volumes:
  sassfr_postgres_data:
